services:
  backend:
    container_name: backend
    image: backend-lab1:2024
    build:
      context: TP-1/backend@tmp
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - efrei
    ports:
      - "5432:5432"

  frontend:
    container_name: frontend
    image: frontend-lab1:2024
    build:
      context: TP-1/frontend@tmp
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - efrei
    depends_on:
      - backend
    ports:
      - "8081:80"

networks:
  efrei:
    driver: bridge
